#!/usr/bin/env bash
# Build bcs-zig WASM module for @unconfirmed/bcs
#
# Prerequisites:
#   - Zig >= 0.14.0
#   - bcs-zig repo at ../bcs-zig (sibling directory)
#
# Output: wasm/bcs.wasm (~5-10KB)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BCS_ZIG="${REPO_ROOT}/../bcs-zig"

if [ ! -f "$BCS_ZIG/src/bcs.zig" ]; then
  echo "Error: bcs-zig not found at $BCS_ZIG"
  echo "Clone it: git clone <bcs-zig-repo> $BCS_ZIG"
  exit 1
fi

echo "Building bcs-zig WASM..."

zig build-exe \
  -target wasm32-freestanding \
  -OReleaseSmall \
  --dep bcs \
  -Mroot="$SCRIPT_DIR/bcs.zig" \
  -Mbcs="$BCS_ZIG/src/bcs.zig" \
  -rdynamic \
  --cache-dir /tmp/zig-cache \
  --global-cache-dir /tmp/zig-global-cache

# Zig outputs root.wasm in current directory
mv root.wasm "$SCRIPT_DIR/bcs.wasm"

SIZE=$(wc -c < "$SCRIPT_DIR/bcs.wasm" | tr -d ' ')
echo "Built wasm/bcs.wasm ($SIZE bytes)"

# Generate base64-embedded TypeScript module
echo "Generating src/wasm-binary.ts..."
BASE64=$(base64 < "$SCRIPT_DIR/bcs.wasm" | tr -d '\n')
cat > "$REPO_ROOT/src/wasm-binary.ts" << TSEOF
// Auto-generated by wasm/build.sh — do not edit
// bcs-zig WASM module ($SIZE bytes)
export const WASM_BASE64 = "$BASE64";
TSEOF

echo "Done."
